receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4317"
exporters:
  logging:
    logLevel: $LOGGING_EXPORTER_LOG_lEVEL
  otlp:
    endpoint: $OTLP_EXPORTER_ENDPOINT
    compression: none
    tls:
      insecure: true
service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [logging, otlp]
    traces:
      receivers: [otlp]
      exporters: [logging, otlp]
    logs:
      receivers: [otlp]
      exporters: [logging, otlp]
