receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4317"
  otlp/mtls:
    protocols:
      http:
        endpoint: 0.0.0.0:5317
        tls:
          client_ca_file: $MTLS_CLIENT_CERTIFICATE
          cert_file: $MTLS_SERVER_CERTIFICATE
          key_file: $MTLS_SERVER_KEY
exporters:
  logging:
    logLevel: $LOGGING_EXPORTER_LOG_lEVEL
  otlp:
    endpoint: $OTLP_EXPORTER_ENDPOINT
    compression: none
    tls:
      insecure: true
service:
  pipelines:
    metrics:
      receivers: [otlp, otlp/mtls]
      exporters: [logging, otlp]
    traces:
      receivers: [otlp, otlp/mtls]
      exporters: [logging, otlp]
    logs:
      receivers: [otlp, otlp/mtls]
      exporters: [logging, otlp]
