on:
  workflow_dispatch:
    inputs:
      version:
        description: The version to tag the release with, e.g., 1.2.0, 1.2.1-alpha.1
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_release_version: ${{ github.event.inputs.version }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: burrunan/gradle-cache-action@v1.5
        with:
          job-id: jdk8
          remote-build-cache-proxy-enabled: false
          arguments: build --stacktrace
          properties: |
            enable.docker.tests=true
      - name: Publish artifacts
        run: ./gradlew final --stacktrace
        env:
          CI: true
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
